import { Link } from 'react-router-dom';
import { ArrowUpRight, Building2, Factory, House, Settings2, ScanLine, Layers3 } from 'lucide-react';
import { services } from '../data/site';
import { PageHeading, Button, Picture, SectionHeading, CTASection } from '../components/ui';
export function About() {
  return <><PageHeading eyebrow="Hakkımızda" title={<>Güvenle açılan<br />bir geleceğe.</>} text="Şanlıurfa’da asansör kapı sistemleri üretiyor, mühendislik ve titiz işçiliği aynı noktada buluşturuyoruz." /><section className="section container company-story"><div className="story-visual"><Picture name="door-enhanced" alt="Mevcut görselden iyileştirilmiş temsili asansör kapısı" priority /><span>HAS DOOR / ASANSÖR KAPI SİSTEMLERİ</span></div><div><p className="eyebrow">ÜRETTİĞİMİZ HER DETAYDA</p><h2>Kaliteyi bir çalışma biçimi olarak görüyoruz.</h2><p>Has Door, Şanlıurfa merkezli, asansör kapı sistemleri üretimi alanında faaliyet gösteren bir imalat firmasıdır. Kalite, güvenlik ve dayanıklılığı temel prensip edinerek konut, ticari yapı ve endüstriyel projeler için modern kapı çözümleri üretiyoruz.</p><p>Üretim süreçlerimizde teknolojiyi, mühendislik bakış açısını ve titiz işçiliği bir araya getiriyoruz. Uzun ömürlü kullanım, performans ve estetik, ürün geliştirme yaklaşımımızın merkezinde yer alıyor.</p><p>Proje ihtiyaçlarına özel çözümler sunuyor; üretimden teslimata kadar güvenilir bir iş ortağı olmayı hedefliyoruz.</p><Button to="/iletisim" variant="outline">Tanışalım</Button></div></section><section className="values-section"><div className="container section"><SectionHeading eyebrow="ÇALIŞMA ANLAYIŞIMIZ" title="Sağlam bir yaklaşım.<br />Ortak bir hedef." /><div className="values-grid">{[[Settings2,'Mühendislik bakışı','Her ürünü, yapının teknik gereksinimleri ve kullanım deneyimiyle birlikte değerlendiriyoruz.'],[Layers3,'Üretimde özen','Kalite ve dayanıklılığı malzeme seçiminden işçiliğe kadar tüm sürecin odağında tutuyoruz.'],[ScanLine,'Müşteri odaklılık','İhtiyaçları dinliyor, projeye özel çözümlerle uzun vadeli bir çalışma ilişkisi kurmayı hedefliyoruz.']].map(([Icon,title,text]) => <article key={title}><Icon size={28} strokeWidth={1.3} aria-hidden="true" /><h3>{title}</h3><p>{text}</p></article>)}</div></div></section><section className="section container vision-grid"><div><p className="eyebrow">VİZYONUMUZ</p><h2>Yerelden geleceğe.</h2><p>Türkiye’de asansör kapı sistemleri sektörünün öncü markalarından biri olmak ve kaliteli üretim anlayışımızı uluslararası pazarlara taşımak.</p></div><div><p className="eyebrow">MİSYONUMUZ</p><h2>Kalıcı değer üretmek.</h2><p>Güvenli, dayanıklı ve yenilikçi ürünlerle müşterilerimize uzun yıllar değer katmak. Kaliteyi, güveni ve sürdürülebilir üretimi ön planda tutmak.</p></div></section><CTASection /></>;
}
export function Services() {
  return <><PageHeading eyebrow="Hizmetler" title={<>Bir üründen fazlası.<br />Birlikte geliştirilen çözümler.</>} text="Kapı sistemi üretiminden projenize uygun seçime kadar, ihtiyaçlarınıza odaklanan bir çalışma anlayışı." /><section className="section container">{services.map((s,i) => <article className="service-detail" key={s.id} id={s.id}><div className="service-detail-number">0{i+1}</div><div><p className="eyebrow">HAS DOOR ÇÖZÜMLERİ</p><h2>{s.title}</h2><p>{s.text}</p><p>{s.detail}</p><Button to={s.to} variant="outline">{s.cta}</Button></div><div className="service-detail-art">{i === 0 ? <Picture name="asansorkapi1" alt="Asansör kapı sistemi mekanizması ve panelleri" /> : i === 1 ? <Picture name="katalog10" alt="Merkezi kat kapısı ölçü çizimi" /> : <div className="material-display"><span /><span /><span /><p>DUVAR / AYNA / TAVAN / ZEMİN</p></div>}</div></article>)}</section><section className="process-section"><div className="container section"><SectionHeading eyebrow="BİRLİKTE İLERLEYELİM" title="Projenizden doğru kapıya." /><ol className="process-grid">{[['İhtiyacı paylaşın','Kapı tipi, ölçüler ve uygulama alanını bize iletin.'],['Detayları değerlendirelim','Ürün seçeneklerini ve proje gereksinimlerini birlikte inceleyelim.'],['Teklifi netleştirelim','Üretim ve teslimat detaylarını görüşerek projenizi ilerletelim.']].map(([title,text],i) => <li key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></li>)}</ol></div></section><CTASection /></>;
}
export function Projects() {
  return <><PageHeading eyebrow="Proje çözümleri" title={<>Farklı yapılar.<br />Aynı özen.</>} text="Konut, ticari yapı ve endüstriyel projeler için asansör kapı sistemleri. Kullanım alanınıza uygun çözümü birlikte belirleyelim." /><section className="section container"><SectionHeading eyebrow="UYGULAMA ALANLARI" title="Yapınızın ihtiyaçlarını merkeze alıyoruz." /><div className="project-sectors">{[[House,'Konut projeleri','Günlük yaşamın doğal bir parçası. Kat ve kabin kapılarını bina yerleşimi ve giriş ölçüleriyle birlikte değerlendirin.','Kapı açılımı, net giriş ve kabin görünümü.'],[Building2,'Ticari yapılar','İş merkezleri ve ticari yapılar için işlev ile estetiği bir arada düşünün. Proje detaylarını teknik ekibimizle paylaşın.','Kullanım senaryosu, kapı tipi ve mimari uyum.'],[Factory,'Endüstriyel projeler','Projenizin teknik gereksinimlerini belirleyerek uygun asansör kapısı seçeneklerini birlikte inceleyin.','Yerleşim, teknik çizimler ve uygulama ölçüleri.']].map(([Icon,title,text,detail],i) => <article key={title}><div className="sector-top"><span>0{i+1}</span><Icon size={55} strokeWidth={1} aria-hidden="true" /></div><h2>{title}</h2><p>{text}</p><p className="sector-detail">{detail}</p><Link className="text-link" to="/iletisim">Projenizi paylaşın <ArrowUpRight size={17} aria-hidden="true" /></Link></article>)}</div><div className="project-brief"><div><p className="eyebrow">PROJE GÖRÜŞMESİ</p><h2>İlk adım için<br />neler gerekli?</h2></div><ul><li>Yapının kullanım amacı ve konumu</li><li>İhtiyaç duyulan kat ve kabin kapısı adedi</li><li>Net giriş ve kapı yüksekliği</li><li>Varsa proje çizimleri ve açılım tercihi</li></ul><Button to="/iletisim">Projemi Görüşmek İstiyorum</Button></div></section><CTASection /></>;
}
export function Privacy({ cookies = false }) {
  return <><PageHeading eyebrow={cookies ? 'Çerezler' : 'Gizlilik'} title={cookies ? 'Çerez ve bağlantı tercihleri.' : 'İletişimde gizliliğiniz.'} text="Bu sayfa, web sitesindeki iletişim formu ve dış hizmetlerin kullanımını açıklar." /><article className="section container legal-copy">{cookies ? <><h2>Site tercihleri</h2><p>Kurumsal sayfalara analitik veya reklam amaçlı çerez eklenmemiştir. Ürün filtreleri sayfa adresindeki parametrelerle çalışır.</p><h2>İsteğe bağlı harita</h2><p>Google Haritalar yalnızca iletişim sayfasındaki “Haritayı yükle” düğmesini seçtiğinizde yüklenir. Bu işlem Google’a bağlantı kurar; Google’ın kendi çerez ve veri işleme koşulları uygulanabilir.</p><h2>Dış bağlantılar</h2><p>WhatsApp ve harita bağlantıları ilgili hizmete yönlendirir. Bu hizmetlerin tercihlerini kendi uygulamalarından veya tarayıcınızdan yönetebilirsiniz.</p><h2>Tarayıcı ayarları</h2><p>Çerez izinlerini tarayıcınızın gizlilik ayarlarından değiştirebilir, daha önce kaydedilmiş site verilerini temizleyebilirsiniz.</p></> : <><h2>İletişim formunda paylaşılan bilgiler</h2><p>Formda adınız, e-posta adresiniz, mesajınız ve isteğe bağlı firma/telefon bilgilerinizi paylaşabilirsiniz. Bu bilgiler, talebinizin Has Door’a iletilmesi ve sizinle iletişim kurulması için kullanılır. Gereksiz kişisel veya hassas bilgi paylaşmayın.</p><h2>Formun iletilmesi</h2><p>Mesajlar mevcut Formspree hizmeti üzerinden iletilir. Gönder düğmesine bastığınızda formda yazdığınız bilgiler bu hizmete aktarılır. Ayrıntıları <a href="https://formspree.io/legal/privacy-policy/" target="_blank" rel="noreferrer">Formspree gizlilik politikasından</a> inceleyebilirsiniz.</p><h2>WhatsApp ve harita</h2><p>WhatsApp üzerinden iletişim kurmayı veya haritayı açmayı seçtiğinizde ilgili hizmetin koşulları geçerlidir. Harita, siz yüklemeyi seçmeden bağlantı kurmaz.</p><h2>Bilgi ve talepleriniz</h2><p>Paylaştığınız bilgilerle ilgili sorularınızı ve taleplerinizi Has Door’a <a href="tel:+905443890185">+90 544 389 01 85</a> numarasından veya <Link to="/iletisim">iletişim sayfasından</Link> iletebilirsiniz.</p></>}</article></>;
}
export function NotFound() {
  return <section className="container not-found"><p className="eyebrow">404 / SAYFA BULUNAMADI</p><h1>Bu kapı başka<br />bir yere açılıyor.</h1><p>Aradığınız sayfa taşınmış olabilir. Ürünlerimize göz atabilir veya bize ulaşabilirsiniz.</p><div className="button-row"><Button to="/">Ana Sayfaya Dön</Button><Button to="/urunler" variant="outline">Ürünleri İncele</Button><Button to="/iletisim" variant="outline">İletişime Geç</Button></div></section>;
}

