import { Link } from 'react-router-dom';
import { ArrowDown, ArrowUpRight, Layers3, MoveHorizontal, ScanLine } from 'lucide-react';
import { Button, Picture, SectionHeading, ProductCard, CTASection } from '../components/ui';
import { products, services } from '../data/site';
export default function Home() {
  return <>
    <section className="home-hero"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow"><span className="live-line" /> MÜHENDİSLİK. ESTETİK. GÜVEN.</p><h1>Her katta kalite.<br /><span>Her detayda<br className="desktop-break" /> Has Door.</span></h1><p className="hero-description">Yapınıza değer katan otomatik asansör kapı sistemleri. Şanlıurfa’da üretim, projenize özel çözümler.</p><div className="button-row"><Button to="/urunler" variant="gold">Ürünleri İncele</Button><Button to="/iletisim" variant="outline-light">Teklif Al</Button></div><a className="hero-scroll" href="#cozumler"><ArrowDown size={16} aria-hidden="true" /> ÇÖZÜMLERİMİZİ KEŞFEDİN</a></div><div className="hero-visual"><Picture name="door-enhanced" alt="Mevcut görselden iyileştirilmiş, temsili cam panelli asansör kapısı" priority /><div className="hero-image-caption"><span>HAS DOOR<br /><strong>Asansör kapı sistemleri</strong></span><span className="caption-cross">+</span></div><span className="vertical-note">TASARIMDAN ÜRETİME, HER DETAYDA ÖZEN</span></div></div></section>
    <section className="principles" aria-label="Çalışma yaklaşımımız"><div className="container principles-grid">{[[Layers3,'Üretim odaklı','Asansör kapı sistemlerinde uzmanlık'],[MoveHorizontal,'Projeye uygun','Merkezi ve teleskopik çözümler'],[ScanLine,'Detaylara özen','İşlev ve estetiği buluşturan yaklaşım']].map(([Icon,title,text],i) => <div key={title}><span className="principle-number">0{i+1}</span><Icon size={25} strokeWidth={1.3} aria-hidden="true" /><div><h2>{title}</h2><p>{text}</p></div></div>)}</div></section>
    <section id="cozumler" className="section container"><SectionHeading eyebrow="ÜRÜN AİLEMİZ" title={<>Doğru kapı.<br />Güçlü bir başlangıç.</>} text="Farklı açılım biçimleri, ortak bir kalite anlayışı. Projenize uygun kat ve kabin kapılarını keşfedin."><Link className="text-link" to="/urunler">Tüm ürünleri incele <ArrowUpRight size={19} aria-hidden="true" /></Link></SectionHeading><div className="product-grid home-products">{products.slice(0,3).map((p,i) => <ProductCard key={p.slug} product={p} index={i} />)}</div></section>
    <section className="studio-section"><div className="container studio-grid"><div className="studio-art" aria-hidden="true"><div className="studio-frame"><div className="studio-ceiling" /><div className="studio-wall left-wall" /><div className="studio-back"><span /><span /><span /></div><div className="studio-wall right-wall" /><div className="studio-floor" /></div><div className="material-swatches"><span /><span /><span /><span /></div><span className="studio-art-label">MALZEME. DOKU. KARAKTER.</span></div><div className="studio-copy"><p className="eyebrow">HAS DOOR / TASARIM STÜDYOSU</p><h2>Sizin çizginiz.<br />Sizin kabininiz.</h2><p>Malzemeleri bir araya getirin. Duvarlardan tavana, aynadan zemine kadar seçimlerinizi canlı 3D önizlemede keşfedin.</p><ul className="studio-features"><li><span>01</span> Duvar ve panel malzemeleri</li><li><span>02</span> Ayna, tavan ve zemin seçenekleri</li><li><span>03</span> Etkileşimli üç boyutlu önizleme</li></ul><Button to="/kabin-tasarla" variant="gold">Kabinini Tasarla</Button></div></div></section>
    <section className="section container"><SectionHeading eyebrow="NASIL ÇALIŞIYORUZ?" title="İhtiyacınızı anlar, detayları birlikte çözeriz." /><div className="service-list">{services.map((s,i) => <Link to={s.to} className="service-row" key={s.id}><span className="row-number">0{i+1}</span><h3>{s.title}</h3><p>{s.text}</p><ArrowUpRight size={27} strokeWidth={1.3} aria-hidden="true" /></Link>)}</div></section>
    <section className="about-teaser"><div className="container about-teaser-grid"><div><p className="eyebrow">BİZ HAS DOOR’UZ</p><h2>Güven, her detayda<br />yeniden üretilir.</h2></div><div><p>Şanlıurfa merkezli Has Door olarak konut, ticari yapı ve endüstriyel projeler için asansör kapı sistemleri üretiyoruz. Mühendislik bakış açısını titiz işçilikle bir araya getiriyoruz.</p><Link className="text-link" to="/hakkimizda">Bizi yakından tanıyın <ArrowUpRight size={18} aria-hidden="true" /></Link></div></div></section><CTASection />
  </>;
}

